import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Boonstra Application Development",
  description: "Generated by Boonstra Application Development",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <header>
            <ol id="company-logo">
                <li>
                    boonstr
                </li>
                <li>
                    application
                </li>
                <li>
                    development
                </li>
            </ol>
            <ul className="menu">
                <li>
                    <Link href="/rienk-boonstra">Rienk Boonstra</Link>
                </li>
                <li>
                    <Link href="/java-kotlin-development">Java/Kotlin</Link>
                </li>
                <li>
                    <Link href="/react-nextjs-development">React/Nextjs</Link>
                </li>
                <li>
                    <Link href="/artificial-intelligence">Artificial Intelligence</Link>
                </li>
                <li>
                    <Link href="/opdrachtgevers">Opdrachtgevers</Link>
                </li>
                <li>
                    <Link href="/contact">Contact</Link>
                </li>
            </ul>
        </header>
        <main>
            {children}
        </main>
      </body>
    </html>
  );
}
